alias _='sudo -E'
alias '..'='cd ..'
alias '...'='cd ../..'
alias '....'='cd ../../..'
alias cat='bat'
alias ls='exa --icons'
alias ll='exa --icons -alF'
alias la='exa --icons -la'
alias bd='batdiff'

# Containerd
alias docker='nerdctl'

# Git
alias g=git
alias st='git status'
alias push='git push'
alias pull='git pull'
alias log='git log'
alias ci='git commit'
alias co='git checkout'
alias dif='git diff'
alias rs='git reset'
alias rb='git rebase'
alias fixup='git fixup'
alias branch='git branch'
alias branches='git branch -a'
alias tag='git tag'
alias up='git up'
alias sync='git sync'
